global:
  scrape_interval: 5s

scrape_configs:
  - job_name: stream-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - host.docker.internal:8094

  - job_name: video-ingest-agent
    metrics_path: /metrics
    static_configs:
      - targets:
          - video-ingest-agent:8098
