pluginManagement {

    repositories {
        gradlePluginPortal()
        mavenCentral()
    }

}


plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.10.0'
}


rootProject.name = 'smart-surveillance-platform'


include(
        'common:common-events',
        'common:common-kafka',
        'common:common-logging',

        'gateway:camera-gateway',

        'services:camera-service',
        'services:recording-service',
        'services:notification-service',
        'services:analytics-service',
        'services:search-service'
)
