spring:
  application:
    name: stream-service

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: stream-service
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: com.coltrack.events

server:
  port: 8094

camera-service:
  url: http://localhost:8091

stream:
  hls:
    #path: /opt/surveillance/hls
    path: ./data/hls
