server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:

            - id: websocket-service
              uri: ws://localhost:8096
              predicates:
                - Path=/ws/**

            # HLS video stream
            #
            - id: hls-stream
              uri: http://localhost:8094
              predicates:
                - Path=/hls/**

            #
            # Camera Service
            #
            - id: camera-service
              uri: http://localhost:8091
              predicates:
                - Path=/api/v1/cameras/**
              filters:
                - RewritePath=/api/v1/cameras(?<segment>/?.*), /api/cameras${segment}

            #
            # Stream Service
            #
            - id: stream-service
              uri: http://localhost:8094
              predicates:
                - Path=/api/v1/streams/**
              filters:
                - RewritePath=/api/v1/streams(?<segment>/?.*), /api/streams${segment}


            #
            # Recording Service
            #
            - id: recording-service
              uri: http://localhost:8095
              predicates:
                - Path=/api/v1/recordings/**
              filters:
                - RewritePath=/api/v1/recordings(?<segment>/?.*), /api/recordings${segment}

            #
            # Recording playback
            #
            - id: recording-playback
              uri: http://localhost:8095
              predicates:
                - Path=/recordings/**

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - gateway

  endpoint:
    gateway:
      access: read-only
